### ISSUE TITLE
Observation Duplication

### ISSUE THREAD

**Issue by asewnath** [GEOS-ESM/swell#175]
For the surface ship winds, the duplicate factors for UFO and GSI are not equal, which is affecting the obserror.
<img width="444" alt="Screenshot 2023-05-03 at 3 54 29 PM" src="https://user-images.githubusercontent.com/14252652/236032839-7c5ea0b6-73b4-49d2-9e6d-41038a7ca96f.png">

If we were to get rid of the duplicate check filter and multiply the GSI duplicate factor to the final UFO obs error, the obs errors would be in perfect agreement.

Taking a closer look at the files, there are some locations where the GSI reports an extra duplicate that doesn't exist for the UFO, so we are reviewing the ioda converters and file combining strategies for any discrepancies.

**Comment by gmao-jjin3** [comment]
@asewnath Thank you very much. Can you post the numbers of each conventional type in those separated IODA files and those combined IODA files? That shows one of the reasons that we cannot get same duplicate factors in UFO as in GSI for some observations: The IODA combine program merge some surface pressure and temperature observations if those data have same locations, altitude/pressure, time, station_ID/type

**Comment by asewnath** [comment]
Taking a look at the kx counts for individual and combined files:

individual files: /gpfsm/dnb31/jjin3/jedi/For_others/x0044.jj_20230201.iodav3/conv/*
combined file: /gpfsm/dnb31/jjin3/jedi/For_others/x0044.jj_20230201.iodav3/gsidiag_2_ufo/ncdiag/ob/x0044/PT6H/2020-12-15/x0044.sfcship.2020-12-14T21:00:00Z.nc4

sfcship_q_obs_2020121500.nc4
[180 183]
Individual file:  180 :  3762
Combined file:  180 :  3762
Individual file:  183 :  2787
Combined file:  183 :  2787


sfcship_tv_obs_2020121500.nc4
[180 183]
Individual file:  180 :  3762
Combined file:  180 :  3762
Individual file:  183 :  2788
Combined file:  183 :  2788


sfcship_ps_obs_2020121500.nc4
[180 183]
Individual file:  180 :  14933
Combined file:  180 :  14815
Individual file:  183 :  3782
Combined file:  183 :  3782


sfcship_uv_obs_2020121500.nc4
[280 282 284]
Individual file:  280 :  7906
Combined file:  280 :  7906
Individual file:  282 :  210
Combined file:  282 :  210
Individual file:  284 :  3696
Combined file:  284 :  3696


sfcship_tsen_obs_2020121500.nc4
[180 183]
Individual file:  180 :  4017
Combined file:  180 :  3919
Individual file:  183 :  977
Combined file:  183 :  977

**Comment by gmao-jjin3** [comment]
A summary of issues in handling duplicated observations in UFO.

1) There are independent observations spaces for conventional surface sation, sondes, marine ships, etc. in UFO and there is no communication between them in UFO operators and filters.  For example, there are co-loated surface pressure (named stationPressure in UFO) in both Sondes and Surface data files. However, those data are saved in different files and processed in different UFO observational spaces. As a result, those data cannot be counted as duplicated observations. https://github.com/GEOS-ESM/swell/issues/78#issuecomment-1373909089.  In addition, air temperature and virtual temperature are in independent observational spaces in UFO.  However, these two temperature observational types are one observational type in GSI.  That results in differences in counting co-located temperature data and then causes differences in error inflation factors in UFO and GSI. 
 
2) The IODA converter combining program sometimes fails to combine observations correctly.  Surface pressure, temperature, humidity, and winds are saved into separate NetCDF files by GSI since they have different operators.  IODA converter transform them into different files and them combine these different variables into different files such as files for all sondes data. The python program uses locations, altitude, time information to combine those data.  A machine round-off error can make those information different for observations at the same location.  For example, some temperature and air pressure data made at the same location are treated as as in different observational profiles by the IODA converter. https://github.com/GEOS-ESM/swell/issues/78#issuecomment-1335917623.  Another example, there are fewer surface ship surface pressure (Ps) observations in the combined program than in the individual files as reported above in this issue. https://github.com/GEOS-ESM/swell/issues/175#issuecomment-1535185533 
 
3) There are duplicated reports, likely because of human errors, in original meteorological data files or bufr files. Meta found that some data are made at the same location and time, but have different values at some heigh levels. https://github.com/GEOS-ESM/swell/issues/78#issuecomment-1415155632.  Those observations are processed with large weights  through duplication-factor check in GSI.  However, these data are combined into single profiles and are not processed with large errors in UFO.

In short, duplicated observation checking in UFO is not able to find exactly same co-located observations as GSI does even though it can find most of the co-located observations in UFO.  Some observational error are different from these values in GSI.    

==== Some changes in GSI which could make duplicate factors match in UFO and GSI for some data types. Note, those changes were made merely for investigation and  were not merged into GSI. https://github.com/GEOS-ESM/GEOSana_GridComp/pull/126 ====
A few minor changes in order to make inflated observational errors of conventional observations identical to those values in GEOS.
(1) Keep only one of those conventional observations which are made at the same locations, level, and time, and discard the rest of them. As a result, we can avoid losing those data in IODA converter, and have same duplicate factors in JEDI as in GSI.
(2) Determine duplicate factors by single precision geo-location values since single precision values are saved in NC_Diag files and then used in JEDI/UFO.
(3) Not to consider sensible temperature and virtual temperature made at same locations as duplicated observations.
