### ISSUE TITLE
Eva Increment Task

### ISSUE THREAD

**Issue by asewnath** [GEOS-ESM/swell#309]
@rtodling Talking to @Dooruk, we think that it'll be best to add another eva task to swell called `EvaIncrement`. This task will solely handle increment diagnostics (instead of relying on another task, such as EvaObservations).

I may wait until 3dvar_atmos work is merged before I make this change, if that makes sense to everyone.

**Comment by rtodling** [comment]
First let me say: thanks for this. Let me toss another idea here - not sure how simply that is. In the case of observations statistics  we have the capability to compare JEDI results w/ those from GSI since the GSI results are (for now) stored in the IODA files. This is very convenient while we are all in this mode of testing things out.

Similarly, it would be nice to be able to compare increments - for example make a difference plot between GSI temperature at 500 mb vs the same from JEDI. When I do things my hand I have a whole way of doing that - but that's unfortunately, grads-based and not very portable. 

Doing this comp of the increments is a little tricky because nowhere in JEDI we have access to the GSI increments. However, we could think of the increment as a "verification dataset" - something that lives outside the swell/jedi framework. 

We could have a yaml file that is exported into the EVA that allows the user to simply specify the location of the verification file - by hand  - after the suite has been created. Once that verification dataset is anything other than /dev/null ... EVA could kick in doing comps (we'd have entries similar to the obs/hofx stuff that diffs variables and all ...

Just something to think about for now ...

**Comment by Dooruk** [comment]
Thanks for working on this @asewnath. Just to repeat what I mentioned her already, formats for marine and atmosphere increment outputs are different. Which means they are handled differently EVA (SOCA restart vs. latlon classes), that will add another layer of complexity.

@rtodling, that's a good idea. I just took a look at EVA, and there is a data class for GSI. 

https://github.com/JCSDA-internal/eva/blob/develop/src/eva/data/gsi_obs_space.py

So, technically this could be added similar way you added increment to the eva obs yaml. However, I'm not sure how GSI files are organized and how else this would entail. Perhaps we can discuss this during JEDI Wednesday meeting so others can chime in.

**Comment by Dooruk** [comment]
For inspiration:

https://github.com/NOAA-EMC/GDASApp/tree/develop/ush/eva

**Comment by asewnath** [comment]
Note: there would probably be a similar mechanism needed for comparing JEDI/GSI geovals in terms of a GSI verification set
