### ISSUE TITLE
SE: Swell not to invert ordering of statements from template to master yamls 

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#330]
There is a rather annoying feature in swell - I vaguely recall it didn't use  to be like this - where the original yaml settings get flipped and swapped in such a way that the end, grand-master yaml becomes unreadable and very hard to edit - thus making it is painful to debug - debugging typically requires  re-creating the experiment anew just because it's for a user to figure out the proper indentation by hand. 

This is PR expresses the hope and desire that this be reversed and the software be placed to keep the ordering provided in the template yamls.

**Comment by Dooruk** [comment]
According to my quick search there are different loaders in `yaml`, i.e.,  `load(yaml_data, Loader=yaml.CLoader)`. The solution might be as simple as using `cLoader`, which I don't think is the default, just needs to be tested.

@rtodling was the original approach you referring to used `orderedDict` instead of using dictionaries?

**Comment by Dooruk** [comment]
Well, this might be rather obvious but YAML configs are getting reorganized in ascending order alphabetically after templates are filled. So, there is some order 😄
