### ISSUE TITLE
YAML Configuration | AVHRR

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#64]
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] Metop-A
- [x] NOAA-18

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] Metop-A
- [x] NOAA-18

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] Metop-A
- [x] NOAA-18

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] Metop-A
- [x] NOAA-18

## Agreement with GSI using Swell

- [ ] Metop-A
- [ ] NOAA-18

## JEDI PRs

- [ ] TBD

## Current issues:

- Pending PR needed in UFO

**Comment by HamidehGMAO** [comment]
Hi @gmao-jjin3, looking again at the avhrr obs and geovals here /gpfsm/dnb31/jjin3/jedi/For_others/x0044j/gsidiag_2_ufo/ncdiag/ob/x0044j/PT6H/2020-12-15, I see the the AVHRR files have been generated on May 12th, and you have more recent run for other radiances like gmi. I was wondering if these AVHRR files have the same issue you explained this morning? or they should be fine

**Comment by gmao-jjin3** [comment]
These files should be fine for testing. Wei's new issue is about observational error in IASI data. I don't think it is an issue in AVHRR data since we don't consider correlated observational errors for these data. But, please let me know if you have any issues.

**Comment by HamidehGMAO** [comment]
OK, Sounds good. Thanks for the in formation. Also, I was wondering if you could point me to the background data you used for creating these geoval data. I was wondering if the surface temperature here is really Skin temperature or not. Thanks

**Comment by gmao-jjin3** [comment]
Here is the GSI program writing out diagnostic data:
/discover/nobackup/jjin3/GEOSadas_git/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/setuprad.f90

Here is the Python code to convert GSI outputs to UFO testing files:
/discover/nobackup/jjin3/jedi/ioda-bundle/iodaconv/src/gsi-ncdiag/gsi_ncdiag.py_20220512

**Comment by HamidehGMAO** [comment]
Thanks a lot Jianjun, I will take a look.

**Comment by HamidehGMAO** [comment]
you can find the plots here: "https://docs.google.com/presentation/d/1HAd8AqAQheEm1up8KbKQoW69TCqVGIe0gGhy4JS0VJQ/edit#slide=id.g12e603c7e54_0_62"

**Comment by gmao-jjin3** [comment]
@HamidehGMAO , can you try new data in /discover/nobackup/jjin3/jedi/For_others/x0044.jj_20220619
Search  "avhrr3" in that directory.

**Comment by gmao-jjin3** [comment]
@HamidehGMAO  New UFO testing files are in /discover/nobackup/jjin3/jedi/For_others/x0044.jj_20220708.nst_gsi/
These are made from an x0044-like run, but with "NST_GSI=0".  Its results are  in /archive/u/jjin3/x0044.jj_20220708.nst_gsi/ .

**Comment by gmao-wgu** [comment]
@HamidehGMAO @gmao-jjin3 @danholdaway @gmao-yzhu @rgelaro  A bug was found and fixed in cloud detection for AVHRR. It is related the biases which were accounted twice when calculating OMF for cloud detection. The following plots show the impacts.

Before the bug fixes:
![avhrr_metop-a Swell_Obs_Number O-F_BC_QC ch2 ps](https://user-images.githubusercontent.com/59488002/187764023-028da443-b0c1-43b7-8645-d7011a39f06f.png)

![avhrr_metop-a Swell_Obs_Number O-F_BC_QC ch3 ps](https://user-images.githubusercontent.com/59488002/187764116-1cebe291-5f6d-4903-95b1-328c9afa8a09.png)

After the bug fixes:
![avhrr_metop-a Swell_Obs_Number O-F_BC_QC ch2 ps (1)](https://user-images.githubusercontent.com/59488002/187764467-449def76-4198-41d7-9b6a-8c293d04c922.png)
![avhrr_metop-a Swell_Obs_Number O-F_BC_QC ch3 ps (1)](https://user-images.githubusercontent.com/59488002/187764501-84713510-1df5-4cef-84d0-930c3a6916d0.png)

However, there is still one point that has the mismatch between the GSI and UFO in hofx resulting from the CRTM simulation which you can see from the following plots:
![avhrr_metop-a Swell_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch2 ps](https://user-images.githubusercontent.com/59488002/187765615-258b716f-3734-41ed-bb46-fd0a454c3c79.png)
![avhrr_metop-a Swell_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch3 ps](https://user-images.githubusercontent.com/59488002/187765769-11ac75da-44bc-483f-b16c-32120874332a.png)

**Comment by HamidehGMAO** [comment]
Thanks a lot @gmao-wgu. Looks great.

**Comment by gmao-wgu** [comment]
> Thanks a lot @gmao-wgu. Looks great.

My pleasure @HamidehGMAO

**Comment by rgelaro** [comment]
Excellent, thanks.

**Comment by HamidehGMAO** [comment]
Thanks a lot, Jianjun. I really appreciate it.
________________________________
