### ISSUE TITLE
YAML Configuration | Satwind

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#73]
## Agreement with GSI using GeoVaLs in UFO (Hofx)

- [x] Done

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] Done

## Agreement with GSI using Swell

- [ ] Done

**Comment by gmao-jjin3** [comment]
@asewnath  I think the "inflation" is to handle "ratio_errors" in setupw.f90. If you can program "ratio_errors" in your yaml file, however, you may not need this "inflation".  I add Meta in this message. @gmao-msienkie

**Comment by gmao-jjin3** [comment]
@asewnath  It turns out that it is not straight forward to write background air-pressure for winds as for radiance data in GSI.  @danholdaway is there a tool to write out geoval in Swell?

**Comment by danholdaway** [comment]
We can write the GeoVaLs out from swell but I'm not sure that's useful in this context. What is needed is to run the UFO tests where we take the same inputs and outputs from GSI and make sure the results are the same. Can you elaborate on the issue? I believe that GeoVaLs have been written out by GSI for the purpose of testing conventional data. Perhaps there is a branch on the NOAA side that has this capability? Is it worth mentioning at a JCSDA obs meeting or discussing with Emily?

**Comment by gmao-jjin3** [comment]
@danholdaway **The Python IODA converter requires "air_pressure" information in GSI diagnostic files. Here is an error message of the converter:**

> Platform:satwind Var:uv #Obs:3056162
> ProcessedL 3056162 Conventional obs processed to: testrun/satwind_obs_2020121500.nc4
> Platform:sfc Var:uv #Obs:71366
> 
> 
> Traceback (most recent call last):
>   File "/discover/nobackup/jjin3/jedi/ioda-bundle/build/bin/test_gsidiag.py", line 67, in <module>
>     diag.toGeovals(outdir)
>   File "/gpfsm/dnb31/jjin3/jedi/ioda-bundle/build/lib/pyiodaconv/gsi_ncdiag.py", line 655, in toGeovals
>     "nlevs", self.df.dimensions["atmosphere_pressure_coordinate_arr_dim"].size)

I think we need outputs in "setupw.f90" as in "setuprad.f90":
           call nc_diag_data2d("air_pressure", sngl(atmosphere(1)%pressure*r100)) 
           call nc_diag_data2d("air_pressure_levels", sngl(atmosphere(1)%level_pressure*r100) )
However, unlike the processing of radiance data for which this background data type "atmosphere" is derived in crtm_infterface.f90, there is not a calculation of background values at model levels at wind data locations at the moment in "setupw.f90".   It would be great that NOAA can share their programs.

**Comment by CoryMartin-NOAA** [comment]
We had to add it manually, see here: https://github.com/JCSDA-internal/GSI/blob/feature/jedi_gdas/src/gsi/setupw.f90

search `prsltmp2`

**Comment by danholdaway** [comment]
Thanks @CoryMartin-NOAA. @gmao-jjin3 would you be able to try and follow what EMC has done to get that change in?

**Comment by gmao-jjin3** [comment]
Thank you @CoryMartin-NOAA and @danholdaway .  I'll try it.

**Comment by gmao-jjin3** [comment]
@asewnath and @danholdaway  Here are the geoval and obs files
/discover/nobackup/jjin3/jedi/For_others/x0044.jj_20220619/gsidiag_2_ufo/ncdiag/geovals/x0044j/PT6H/2020-12-15/satwind_geoval_2020121500.nc4
/discover/nobackup/jjin3/jedi/For_others/x0044.jj_20220619/gsidiag_2_ufo/ncdiag/ob/x0044j/PT6H/2020-12-15/ncdiag.x0044j.ob.PT6H.satwind.2020-12-14T21:00:00Z.nc4

Let me know if you have any questions.

**Comment by gmao-jjin3** [comment]
@asewnath  I took a look at your file /discover/nobackup/asewnath/satwind_test/satwind_geos_HofX_out.txt which you shared with me. I don't see anything wrong. However, vertical interpolation is just the first step.  I'd suggest you take a look at these two yaml files which I don't know who wrote them, and test these wind data type by type. 
/discover/nobackup/jjin3/jedi/fv3-bundle/ufo/ewok/jedi-gdas/satwind.yaml
/discover/nobackup/jjin3/jedi/fv3-bundle/ufo/ewok/jedi-geos/satwind.yaml
It is going to be tedious since all these quality control processing and error assignments have to be added in yaml files.  @CoryMartin-NOAA @danholdaway and @gmao-yzhu  Is there other or new GFS satwind.yaml which Akira can follow?

**Comment by danholdaway** [comment]
Possibly also worth looking in https://github.com/JCSDA-internal/ufo/tree/develop/ewok/skylab but it looks like a lot of the filters are commented out in these files. But I think the key here is to look through the GSI and try to figure out all the filters that are happening for satwinds. I suspect @gmao-msienkie might be helpful in this regard too.

**Comment by asewnath** [comment]
Confirming that the HofX of GSI and Jedi reaches agreement when Jedi's HofX is multiplied by the `wind_reduction_factor_at_10m` variable found in the associated geoval file.

<img width="619" alt="Screen Shot 2022-08-17 at 2 18 47 PM" src="https://user-images.githubusercontent.com/14252652/185214262-39340034-8469-464d-acd5-32ec991c15d3.png">

<img width="623" alt="Screen Shot 2022-08-17 at 2 20 24 PM" src="https://user-images.githubusercontent.com/14252652/185214311-5bb8613f-a934-4f7c-ae29-bece9ac03ae6.png">

**Comment by danholdaway** [comment]
@asewnath @gmao-msienkie you can use `feature/windfact10` of ufo now. The YAML change looks like: https://github.com/JCSDA-internal/ufo/blob/63e74170127a22dfa46f4e783119f7054f81cc28/test/testinput/instrumentTests/Aircraft_obs/aircraft_gfs_HofX.yaml#L23

**Comment by asewnath** [comment]
<img width="693" alt="Screen Shot 2022-09-30 at 4 24 26 PM" src="https://user-images.githubusercontent.com/14252652/193350838-2702ac51-cdee-4e45-94b5-5ce135b73bbc.png">

This is where I ended up today. The qc yaml with added filters is here: /discover/nobackup/asewnath/DanJediUfoTests/Config/satwind_geos_qc.yaml

**Comment by asewnath** [comment]
<img width="694" alt="Screen Shot 2022-10-03 at 1 42 22 PM" src="https://user-images.githubusercontent.com/14252652/193643480-818eac78-3468-4801-8718-af7220498bab.png">

working on fixing one kx at a time as Wei suggested. 247 filters look done

**Comment by gmao-wgu** [comment]
@asewnath @danholdaway @gmao-jjin3 I can duplicate your plot. However, instead of using GsiFinalObsError > 0, we could use GsiUseFlag to determine whether or not the obs would pass QC in the GSI, If I use GsiUseFlag=1,  I get the different plot as shown in the following.
    
![density_qced_omb_vs_gsiomb_kx247](https://user-images.githubusercontent.com/59488002/195218969-7e43f561-fefe-4bf9-ba3f-928cb433fd3c.png)

To get the idea which one is correct, I run the case with full size of testing files so that I could compare with the GSI output directly under /archive/u/jjin3/x0044.jj_20221009. The followings are what I get:

With GsiFinalError > 0,
      
![density_qced_omb_vs_gsiomb_kx247 (1)](https://user-images.githubusercontent.com/59488002/195220796-550e32c4-ac3d-46f9-9a4e-fd9b09dce9c4.png)

with GsiUseFlag =1,
 
![density_qced_omb_vs_gsiomb_kx247 (2)](https://user-images.githubusercontent.com/59488002/195220948-aa70dd90-51cc-44e9-90a6-b57d77845fc6.png)

If you check the GSI output from the file *ana_stats*, you could tell 44608 should be the correct number for kx=247.

**Comment by asewnath** [comment]
### Duplicate Filter Requirement

The GSI contains logic for handling duplicate observations by inflating errors when duplicates occur. As of now, there doesn’t seem to be a UFO filter that corresponds to this duplicate observation handling. The following lines represent the duplicate logic found in `setupw.f90`:

- all values for the array `dup` are set to one
- two loops through all observations using k and l where `l=k+1`
- given that `twodvar_regional` is set to false, the boolean `duplogic` is set to one:
    - if observation k and observation l have the same latitude, longitude, and pressure
    - if their obs errors are less than 1000
    - if they are both used (determined by the variable `muse`)
- if `duplogic` is one then:
    - a variable `tfact` is set to the minimum between one and the absolute value of observation time of observation k minus observation time of observation l divided by `dfact1`
        - `tfact=min(one,abs(data(itime,k)-data(itime,l))/dfact1)`
    - the value in the array `dup` for a given index is updated with the addition of one minus the subtraction of one and `dfact` which is multiplied by `tfact` squared
        - `dup(k)=dup(k)+one-tfact*tfact*(one-dfact)`
        - `dup(l)=dup(l)+one-tfact*tfact*(one-dfact)`
    - `dfact1` is the time factor for duplicate obs at the same location for conv data and  is set to three in qcmod.
    - `dfact` is the factor for duplicate obs at same location for conv data and is set to zero.
- Later in the code, `dup` is used to update `ratio_errors`: 
    - `ratio_errors = ratio_errors/sqrt(dup(i))`
- `ratio_errors` is then used to update the final obs error given certain conditions
```
 if (ratio_errors*error>tiny_r_kind) then
     err_final = one/(ratio_errors*error)
 else
     err_final = huge_single
```
@gmao-wgu @gmao-msienkie please let me know if any of this needs to be changed

EDIT: added changes suggested by @gmao-msienkie

**Comment by gmao-msienkie** [comment]
The do-loop for l goes over all of the observations after k+1 - that means every observation (in the GSI subdomain being evaluated on the processor) after k is being compared against observation k. So it is not 'two consecutive observations' but 'an observation and every subsequent observation' with the same latitude, longitude, and pressure.  (Unless of course the observations were sorted by latitude, longitude and pressure, I suppose.)

**Comment by asewnath** [comment]
### Reported Pressure Check

(thank you @gmao-wgu for providing the details for this filter and the duplicate filter above)

A filter is required for checking an observation’s vertical location with respect to surface pressure. If the reported pressure is larger than the surface pressure, the final obs error will be inflated. 

As was noted in the duplicate filter above, the `ratio_errors` variable is used to update the final obs error after it is set. For this check in `setupw.f90`, the ratio_errors are first set to:

`ratio_errors = error/(data(ier,i)+drpx+1.e6*rhgh+4*rlow)`

- `rlow` is defined as `rlow=max(sfcchk-dpres,zero)`
    - `sfcchk` is either set to zero or `sfcchk=log(psges)` based on whether `(z_height .or. sfc_data)` is true
        - `sfc_data` is defined as `(itype >=280 .and. itype < 300) .and. (.not.twodvar_regional)`
        - `psges` is the interpolated output from tintrp2a1 in `tintrp2a.f90`

- `rhgh` is another check to see if the observation is higher than model top
        - `rhgh=max(dpres-r0_001-rsigp,zero)`
        - `rsigp` is `rsig+one`. `rsig` is equal to `nsig`. `nsig` is set to 42 in gridmod.

- `dpres` and `drpx` are set by many different conditions in `setupw` prior to setting `rlow` and `rhgh`.

Again, @gmao-wgu and @gmao-msienkie please let me know if anything needs to be changed

**Comment by CoryMartin-NOAA** [comment]
@bretthoover-noaa have you looked at the pressure check yet in the context of satwinds?

**Comment by BrettHoover-NOAA** [comment]
@CoryMartin-NOAA I have only included initial errors for satwinds in the YAML for the GDASApp PR, this surface pressure check hasn't been a priority for satwinds because even the winds from tracking low clouds don't get close enough to the surface to trigger this error inflation, at least in the test data we've had available, but all of the satwinds need to eventually pass through this filter anyway if we want compliance with GSI. For reference, we are already filtering out any satwind of `type=[244, 247, 257–260]` over a non-ocean surface if the pressure is within some threshold range near the surface. The YAML with these filters is available [here](https://github.com/BrettHoover-NOAA/GDASApp/blob/develop/parm/atm/obs/config/satwind.yaml).

**Comment by gmao-wgu** [comment]
@CoryMartin-NOAA @BrettHoover-NOAA Hi, I was reading the yaml file you guys posted here for satwind. There are some variables in the yaml file like land_type_index_NPOESS@GeoVaLs I was not sure about.  I checked my geoval testing file, we do have land fraction but it has the different name. I was wondering where I can find proper variable names used inside UFO in order to access fields in the testing files?  MetaData/satelliteIdentifier and MetaData/qualityInformationWithoutForecast are another two that have different names in the obs testing file . Thanks!

**Comment by CoryMartin-NOAA** [comment]
@gmao-wgu that is the name that was required for CRTM for the radiance observations (I believe) and it is just being converted in the same way. I'm not 100% sure this is the right approach for satwind, perhaps @BrettHoover-NOAA can comment more

**Comment by gmao-wgu** [comment]
@CoryMartin-NOAA Thanks.  Is there table somewhere we can take a look about how to convert the variable names in the testing files to the names used in UFO?

**Comment by CoryMartin-NOAA** [comment]
I'm not totally sure what you mean, they are supposed to be the same. This may be a case where it is wrong but overall the GeoVaLs need to be the same names.

**Comment by gmao-wgu** [comment]
@CoryMartin-NOAA For example,  "land_area_fraction" in the satwind geoval testing file might be "land_type_index_NPOESS@GeoVaL" in the yaml and "MetaData/qualityInformationWithoutForecast" in the yaml might be corresponding to "satwind_quality_ind_no_fc" in the obs file. So there is name one-to-one conversion somewhere.

**Comment by gmao-jjin3** [comment]
@gmao-wgu  Here is the Python program with which we convert our NetCDF diagnostic outputs to IODA files. 
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/gsi-ncdiag/gsi_ncdiag.py
I'd suggest you check whether we have the output that you need in the setupw.f90 
https://github.com/GEOS-ESM/GEOSana_GridComp/blob/develop/GEOSaana_GridComp/GSI_GridComp/setupw.f90 
If we do, we can certainly add it in IODA files.

**Comment by gmao-wgu** [comment]
@gmao-jjin3 I guess we do have, but I am not sure if we should use the same variable name in the yaml as in the testing files.

**Comment by gmao-wgu** [comment]
@CoryMartin-NOAA @gmao-jjin3 The reason I was looking into it was that I got the error message when I put the following
in the yaml

    - filter: Bounds Check
      filter variables:
      - name: eastward_wind
      test variables:
      - name: eastward_wind@PreUseFlag
     maxvalue: 1
     action:
       name: reject

what is wrong with this?  The value of east_wind@PreUseFlag is either 0 or 100 in the obs test file. I wanted to reject those with 100.

**Comment by gmao-wgu** [comment]
@CoryMartin-NOAA @gmao-jjin3 The above filter was meant to mimic the piece of code in setupw.f90 like 
      

> do i=1,nobs
> muse(i)=nint(data(iuse,i)) <= jiter
> end do

https://github.com/GEOS-ESM/GEOSana_GridComp/blob/develop/GEOSaana_GridComp/GSI_GridComp/setupw.f90

**Comment by gmao-wgu** [comment]
Since we could not use PreUseFlag directly in the YAML, I implemented PreUseCheck filter to reject conventional obs with iuse=-1 in the convinfo resource file or more generally usage .ne. 0 in read_satwnd.f90.  The following plots show the impacts of applying this filter on the satwind, it could be applied to other conventional obs type though  if needed.

Before:
    
![density_qced_omb_vs_gsiomb](https://user-images.githubusercontent.com/59488002/205681291-73db6010-ea5d-4f50-b23a-c10efdfe1dcc.png)

After
![density_qced_omb_vs_gsiomb_preusecheck](https://user-images.githubusercontent.com/59488002/205681375-a9c002b0-d447-47de-9b3d-41e4bb1f105d.png)

It could be seen that the number of satwind obs passing QC in the UFO  is reduced dramatically from 148653 to 88872, much closer to the number in the GSI

**Comment by gmao-wgu** [comment]
The filter for satwind reported pressure check is completed. However, it has no impacts on the obs error inflation since only 36 obs locations where the reported pressures are below the corresponding surface pressures. From the following printout, you could see that all these 36 obs have already been rejected by other filters, so the inflation coefficients are all one.

>  iloc= 3199 rlow= 0.755866 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 3200 rlow= 0.881494 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4048 rlow= 0.0385417 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4324 rlow= 1.21669 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4727 rlow= 0.426886 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4778 rlow= 0.356368 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4839 rlow= 0.830925 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4851 rlow= 0.955399 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 4852 rlow= 1.23319 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 5979 rlow= 0.711679 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 6178 rlow= 0.0931026 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 6181 rlow= 0.232077 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 6182 rlow= 0.493342 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 6214 rlow= 0.930586 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 6245 rlow= 0.113165 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 399942 rlow= 1.31351 rhgh= 0 ObsEror= 5e+08 Qcflag= 11 Inflation Coeff= 1
> iloc= 424024 rlow= 0.636621 rhgh= 0 ObsEror= 5e+08 Qcflag= 11 Inflation Coeff= 1
> iloc= 424131 rlow= 1.80993 rhgh= 0 ObsEror= 5e+08 Qcflag= 11 Inflation Coeff= 1
> iloc= 424169 rlow= 0.24274 rhgh= 0 ObsEror= 5e+08 Qcflag= 11 Inflation Coeff= 1
> iloc= 448082 rlow= 0.923215 rhgh= 0 ObsEror= 5e+08 Qcflag= 11 Inflation Coeff= 1
> iloc= 469060 rlow= 0.00877124 rhgh= 0 ObsEror= 4.708 Qcflag= 11 Inflation Coeff= 1
> iloc= 469081 rlow= 1.35499 rhgh= 0 ObsEror= 4.215 Qcflag= 11 Inflation Coeff= 1
> iloc= 469085 rlow= 1.45159 rhgh= 0 ObsEror= 4.258 Qcflag= 11 Inflation Coeff= 1
> iloc= 479931 rlow= 0.220543 rhgh= 0 ObsEror= 5e+08 Qcflag= 11 Inflation Coeff= 1
> iloc= 501354 rlow= 0.0456673 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 501381 rlow= 1.44193 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 501382 rlow= 0.389372 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 501519 rlow= 0.0674588 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 501526 rlow= 0.139383 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 501623 rlow= 0.26148 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 502665 rlow= 0.830171 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 502666 rlow= 0.317379 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 502737 rlow= 0.223011 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 502747 rlow= 0.0774541 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 502775 rlow= 0.954111 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1
> iloc= 502809 rlow= 0.755946 rhgh= 0 ObsEror= 2.5 Qcflag= 17 Inflation Coeff= 1

**Comment by BrettHoover-NOAA** [comment]
> @CoryMartin-NOAA @gmao-jjin3 The reason I was looking into it was that I got the error message when I put the following in the yaml
> 
> ```
> - filter: Bounds Check
>   filter variables:
>   - name: eastward_wind
>   test variables:
>   - name: eastward_wind@PreUseFlag
>  maxvalue: 1
>  action:
>    name: reject
> ```
> 
> what is wrong with this? The value of east_wind@PreUseFlag is either 0 or 100 in the obs test file. I wanted to reject those with 100.

Hi @gmao-wgu, is `eastward_wind@PreUseFlag` an integer? I believe that `maxvalue` is designed for floats, and the filter configuration for an integer value should be `is_in: 1` instead.

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA Yes, it is.  Bounds Check seemed for float type while PreUseFlag is the integer.

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA could you be more specific about how to use "is_in" in this situation?  Thanks!

**Comment by BrettHoover-NOAA** [comment]
@gmao-wgu You may need to us `Perform Action` rather than `Bounds Check` in that case. I had a `PreQC` flag check in the satwind.yaml file during testing that rejected any `PreQC` value of 9, 12, or 15:
```
  - filter: Perform Action
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    where:
    - variable: PreQC/eastward_wind
      is_in: 9, 12, 15
    action:
      name: reject
```
You could probably use the same format for your test.

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA I already did this as in the folwoing:  
   
  - filter: PreQC
    maxvalue: 3
    action:
      name: reject

However, I still got 148653 this number of obs passing QC in the UFO as compared to 74570 in the GSI

**Comment by BrettHoover-NOAA** [comment]
I just mean you can use the same `Perform Action` and `is_in:` formulation for your specific needs with setting a filter for `PreUseFlag`

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA Okay, Thanks!

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA I tested as you suggested. It works. Thanks!

**Comment by BrettHoover-NOAA** [comment]
@gmao-wgu you're welcome!

**Comment by gmao-wgu** [comment]
The code of SatWindsSPDBCheck.cc needs to be modified. First of all, the wind speed differences might be calculated incorrectly. The following is the part of code to calculate the wind speed differences between the observed and the model simulated:
  

> std::vector<float> u, v;
>   in.get(Variable("eastward_wind@ObsValue"), u);
>   in.get(Variable("northward_wind@ObsValue"), v);
>   // Retrieve Model HofX wind components
>   std::string test_hofx = options_.test_hofx.value();
>   std::vector<float> um, vm;
>   in.get(Variable("eastward_wind@" + test_hofx), um);
>   in.get(Variable("northward_wind@" + test_hofx), vm);
> 
>   // Get original ObsError of eastward_wind (would make little sense if diff from northward)
>   std::vector<float> currentObserr(nlocs);
>   const std::string errgrp = options_.original_obserr.value();
>   in.get(Variable("eastward_wind@"+errgrp), currentObserr);
> 
>   for (size_t jj = 0; jj < nlocs; ++jj) {
>     out[0][jj] = 0.0f;
>     if (u[jj] != missing && v[jj] != missing) {
>       spdb = sqrt(u[jj]*u[jj]+v[jj]*v[jj]) - sqrt(um[jj]*um[jj]+vm[jj]*vm[jj]);

**Comment by gmao-wgu** [comment]
So  you could see that the spdb is the differences of wind speed between observed and OMF wind speed.

**Comment by BrettHoover-NOAA** [comment]
@gmao-wgu `SatWindsSPDBCheck` is a known exception needing an overhaul on the NOAA/NCEP/EMC side, I've been wrestling with it [here](https://github.com/NOAA-EMC/JEDI-T2O/issues/40#issuecomment-1247304834). I believe that the formulation of `spdb` in the code you quoted above is correct, and `spdb` is supposed to represent the difference in speed between the observation and the model background/first-guess. You can see how `spdb` is defined in the GSI in setupw.f90 on Line 898 [here](https://github.com/NOAA-EMC/GSI/blob/8ef658de0c4d528b6cc1f44dcca33653803f9017/src/gsi/setupw.f90#L898).

The problem that I've run into with `SatWindsSPDBCheck` is that in the GSI, if `spdb<0` (i.e. if the observation has a negative speed-bias relative to the model background), the value of `qcgross` is penalized for satwinds based on the observation type and pressure level prior to any comparison of the ratio of `residual/obserr` to `qcgross`. A reference is made to collecting the `gross` value from the user in SatWindsSPDBCheck.cc [here](https://github.com/JCSDA-internal/ufo/blob/6483f7fca7e34df7e2c4d310a7af2c430f18b558/src/ufo/filters/obsfunctions/SatWindsSPDBCheck.cc#L70), but there appears to be no actual collection of input information for `gross` or application of `gross` in the function.

Since so many of the penalties to the GSI=`qcgross` / JEDI=`gross` value are situation-dependent, it would be useful to have all of these penalizations performed within the `SatWindsSPDBCheck` function, with observation type and pressure level as additional inputs.

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA Thanks. I am modifying this part of code to take the consideration of cgross as the function of itype.

**Comment by BrettHoover-NOAA** [comment]
@gmao-wgu I'm glad to hear it! If you don't mind, could you let me know when you have a pull request for those changes? I'd like to be able to coordinate and close my outstanding issue with this function along with any changes you need to make on your end.

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA Sure. I should get the tests done this week.

**Comment by gmao-wgu** [comment]
With the revamped gross check, we got the matched number of observations that pass QC between the GSI and UFO for kx =245, which is shown in the following:

![density_qced_omb_vs_gsiomb_kx245](https://user-images.githubusercontent.com/59488002/207423067-d4665ba5-2cd1-4660-8421-c9345851d7ec.png)

For all kx between 240 and 260, the total number is slightly different due to the slightly different handling of difference check for kx = 244, 257, 258, 259 and 260.

![density_qced_omb_vs_gsiomb (1)](https://user-images.githubusercontent.com/59488002/207424115-2aaa8c21-f1d5-42f0-92ad-4d11a2f96e77.png)

**Comment by BrettHoover-NOAA** [comment]
Hi @gmao-wgu, can you provide a link to where I could view the revamped gross check?

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA I might need to finalize and then push the code changes sometime this week. I will let you know once I get that done.

**Comment by gmao-wgu** [comment]
Here are examples of a few of kx i.e. 244 and 257 that are still different:

     
![density_qced_omb_vs_gsiomb_kx244](https://user-images.githubusercontent.com/59488002/207430119-1946f578-771e-48ea-90e4-d5c0ba5d02b0.png)

![density_qced_omb_vs_gsiomb_kx257](https://user-images.githubusercontent.com/59488002/207430206-76b03759-95f9-4fc0-b0df-78f99270b133.png)

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA, The following is the brief description on how I implemented:

/// \brief Compute the speed background difference (SPDB) of observation-model
///        SatWinds.  If the SPDB is less than zero, then cgross = 0.7cgross
///        when presw is bewteen 300hPa and 400hPa for satwndtype=244 and 245
///        and between 200hPa and 400hPa for satwndtype 253 and 254, then
///        compute a final value of cgross\*ObsError\*abs(OMF of eastward wind or
///        northward wind)/(wind speed residual).That calculation is then used versus a
///        function absolute threshold value in background Check filter to
///        flag obs locations as bad. In regular usage, the test_hofx option
///        would be omitted in order for HofX values are used for model wind
///        components.  Also, an optional group name for the ObsError variable
///        can be supplied if different from ObsErrorData,and its value is
///        bounded by parameters error_min and error_max.
///
///
/// ### Sample YAML configuration for eastward_wind
/// - filter: Background Check
///   filter variables:
///   - name: eastward_wind
//    function absolute threshold:
//    - name: SatWindsSPDBCheck@ObsFunction
//      options:
//        satwndtype: [  240,  241,  242,  243,  244,  245,  246,  247,  248,  249,
//                       250,  251,  252,  253,  254,  256,  257,  258,  259,  260]
//        cgross:     [  2.5,  2.5,  2.5,  1.5,  2.5,  1.3,  1.3,  2.5,  2.5,  2.5,
//                       2.5,  1.3,  2.5,  1.5,  1.5,  2.5,  2.5,  2.5,  2.5,  2.5]
//        error_min:  [  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,
//                       1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4,  1.4]
//        error_max:  [  6.1,  6.1, 15.0, 15.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0,
//                      20.0, 20.0, 20.0, 20.0, 20.0, 20.1, 20.1, 20.1, 20.1, 20.1]
//        variable: eastward_wind
//    action:
//      name: reject
///

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA  This is the code for the revamped gross-check for satwind.
https://github.com/JCSDA-internal/ufo/blob/306dcf427d14225e6b5a60860879c917f0ca0d10/src/ufo/filters/obsfunctions/SatWindsSPDBCheck.cc

https://github.com/JCSDA-internal/ufo/blob/306dcf427d14225e6b5a60860879c917f0ca0d10/src/ufo/filters/obsfunctions/SatWindsSPDBCheck.h

**Comment by gmao-wgu** [comment]
@gmao-jjin3 Thanks for providing the surface types info in the testing file.  If we do difference check on the non-water surface type for kx=244, 247, 257, 258, 259 and 260 as in the GSI, the following is the comparison for kx=257:

Difference Check applied on all surface types, kx =257: 

![density_qced_omb_vs_gsiomb_kx257 (1)](https://user-images.githubusercontent.com/59488002/207951750-493f6bb3-b165-4fe2-81d8-c4f8de151a99.png)

Difference Check applied on non-water surface type, kx = 257:

![density_qced_omb_vs_gsiomb_kx257_isli](https://user-images.githubusercontent.com/59488002/207952370-73b245de-d81e-4251-aca3-634a8efb47dc.png)

So if the difference check is applied on the non-water surface types as in the GSI for kx=257, the number of obs passing QC in UFO is identical to the number in the GSI. For all kx, the difference in total number is also reduced from **163** to **2** as shown in the following:

Difference Check applied on all surface types, all kx between 240 and 260: 
 
![density_qced_omb_vs_gsiomb (2)](https://user-images.githubusercontent.com/59488002/207955756-2969ecba-0060-453f-8ae0-5fb7f0f3017c.png)

Difference Check applied on non-water surface types, all kx between 240 and 260:

![density_qced_omb_vs_gsiomb_isli](https://user-images.githubusercontent.com/59488002/207955920-8b2ab904-1faa-4eee-bb69-de344d2d5782.png)

**Comment by BrettHoover-NOAA** [comment]
@gmao-wgu I appreciate your making the code available! It looks like you're addressing all of the concerns I had with the current implementation of `SatWindsSPDBCheck`. I think the formulation of submitting a list of types and associated `cgross`, `error_min`, and `error_max` values is good, since types can be added or subtracted with no changes to the underlying .cc code.  
  
The penalization of `cgross` based on observation type and pressure level is necessary for matching what is currently in GSI, but I'm curious about your thoughts on how it is being implemented. I think ideally these would be user-defined settings at the YAML level rather than hard-coded into the .cc file, but I can't think of an efficient way to take these modifications out of the .cc code and put them into the YAML. Have you thought about this, any suggestions?

**Comment by gmao-wgu** [comment]
@BrettHoover-NOAA Yes, @gmao-jjin3 has the same concern as you do. We have not found an efficient way to handle this either.

**Comment by danholdaway** [comment]
@gmao-wgu @gmao-jjin3 @asewnath we're getting sooooo close! Just two observations different out of nearly half a million. Great work.

**Comment by gmao-jjin3** [comment]
@asewnath   The duplicate factor for surface pressure needs lat, lon, adjusted_obs_error_input, and the preuse check (iuse check in line 280): 
https://github.com/GEOS-ESM/GEOSana_GridComp/blob/develop/GEOSaana_GridComp/GSI_GridComp/setupps.f90#L288
